import { SearchIcon, MicrophoneIcon } from '@heroicons/react/solid';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>google-clone-nextjs-typescript</title>
        <meta
          name='description'
          content='Generated by create next app using --typescript and tailwind css'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <form className='flex flex-col items-center mt-40'>
        <Image
          width='300'
          objectFit='cover'
          height='100'
          src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/2880px-Google_2015_logo.svg.png'
          alt='google-logo'
        ></Image>
        <div className='flex items-center py-3 px-5 mx-auto mt-5 w-full max-w-[90%] rounded-full border border-gray-200 focus-within:shadow-lg hover:shadow-lg sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='mr-3 h-5 text-gray-500' />
          <input type='text' className='grow focus:outline-none' />
          <MicrophoneIcon className='h-5 text-gray-500' />
        </div>
        <div className='flex flex-col justify-center mt-8 space-y-2 w-[50%] sm:flex-row sm:space-y-0 sm:space-x-4'>
          <button className='btn'>Google Search</button>
          <button className='btn'>I'm Feeling Lucky</button>
        </div>
      </form>

      {/*<main className={styles.main}>*/}
      {/*  <h1 className='pt-3 font-bold text-red-200'>*/}
      {/*    Welcome to <a href='https://nextjs.org'>Next.js!</a>*/}
      {/*  </h1>*/}

      {/*  <p className={styles.description}>*/}
      {/*    Get started by editing <code className={styles.code}>pages/index.tsx</code>*/}
      {/*  </p>*/}

      {/*  <div className={styles.grid}>*/}
      {/*    <a href='https://nextjs.org/docs' className={styles.card}>*/}
      {/*      <h2>Documentation &rarr;</h2>*/}
      {/*      <p>Find in-depth information about Next.js features and API.</p>*/}
      {/*    </a>*/}

      {/*    <a href='https://nextjs.org/learn' className={styles.card}>*/}
      {/*      <h2>Learn &rarr;</h2>*/}
      {/*      <p>Learn about Next.js in an interactive course with quizzes!</p>*/}
      {/*    </a>*/}

      {/*    <a href='https://github.com/vercel/next.js/tree/canary/examples' className={styles.card}>*/}
      {/*      <h2>Examples &rarr;</h2>*/}
      {/*      <p>Discover and deploy boilerplate example Next.js projects.</p>*/}
      {/*    </a>*/}

      {/*    <a*/}
      {/*      href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'*/}
      {/*      className={styles.card}*/}
      {/*    >*/}
      {/*      <h2>Deploy &rarr;</h2>*/}
      {/*      <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>*/}
      {/*    </a>*/}
      {/*  </div>*/}
      {/*</main>*/}

      {/*<footer className={styles.footer}>*/}
      {/*  <a*/}
      {/*    href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'*/}
      {/*    target='_blank'*/}
      {/*    rel='noopener noreferrer'*/}
      {/*  >*/}
      {/*    Powered by{' '}*/}
      {/*    <span className={styles.logo}>*/}
      {/*      <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />*/}
      {/*    </span>*/}
      {/*  </a>*/}
      {/*</footer>*/}
    </div>
  );
};

export default Home;
